version: '3'
services:
  database:
    image: "postgres"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: YSejapt
      POSTGRES_USER: youri
      POSTGRES_DB: docker_database_1
    volumes:
      - ./set.sql:/docker-entrypoint-initdb.d/init.sql


